---
- name: Retrieve release data from portswigger.net
  ansible.builtin.set_fact:
    burp_release_data: "{{ lookup('url', 'https://portswigger.net/burp/releases/data?lastId=-1&pageSize=20') }}"

- name: Identify latest version number for release channel
  ansible.builtin.set_fact:
    _burpsuite_installer_version: "{{ burp_release_data | json_query(version_query) }}"
  vars:
    version_query: >-
      ResultSet.Results[?
        releaseChannels[0] == '{{ burpsuite_channel }}' &&
        builds[?
          ProductId == '{{ burpsuite_edition }}' &&
          ProductPlatform == 'Linux'
        ]
      ].version | sort(@)[-1:] | [0]

- name: Latest version
  ansible.builtin.debug:
    msg: "Latest version for Burp Suite {{ burpsuite_edition | capitalize }} ({{ burpsuite_channel }}) is {{ _burpsuite_installer_version }}"

- name: Identify installer checksum
  ansible.builtin.set_fact:
    burpsuite_installer_sha256_checksum: "{{ burp_release_data | json_query(checksum_query) }}"
  vars:
    checksum_query: >-
      ResultSet.Results[].builds[?
        Version == '{{ _burpsuite_installer_version }}' &&
        ProductId == '{{ burpsuite_edition }}' &&
        ProductPlatform == 'Linux'
      ][].Sha256Checksum
      | [0]
